# Generated by Django 4.2.9 on 2024-01-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('numero_telefone', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('morada', models.CharField(max_length=100)),
            ],
        ),
    ]
