# Generated by Django 3.2.6 on 2021-08-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('morada', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LigaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacontacto_destino', to='contactos.contacto')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacontacto_origem', to='contactos.contacto')),
            ],
            options={
                'unique_together': {('origem', 'destino')},
            },
        ),
    ]
